### ISSUE TITLE
[bug] netease登录框无法弹出

### ISSUE THREAD

**Issue by LuckyXixi** [feeluown/feeluown-netease#35]
bug log
```
[2023-06-22 18:30:38,289 feeluown.utils.dispatch:87] [ERROR]: receiver <weakref at 0x7f8be0264ba0; to 'Nem' at 0x7f8be0221c60> raise error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/feeluown/utils/dispatch.py", line 83, in emit
    func(*args)
  File "/usr/lib/python3.11/site-packages/fuo_netease/nem.py", line 54, in ready_to_login
    cookies, exists = user.cache_get('cookies')
                      ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cache_get'
```

solution to this：
change nem.py +49,50
```
try:
    cookies, exists = user.cache_get('cookies')
    assert exists
except:
    pass
```

**Comment by Candlest** [comment]
The Same
```
 [2023-07-22 20:33:31,709 feeluown.utils.dispatch:87] [ERROR]: receiver <weakref at 0x7ff6901e8e40; to 'Nem' at 0x7ff6901ab130> raise error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/feeluown/utils/dispatch.py", line 83, in emit
    func(*args)
  File "/usr/lib/python3.11/site-packages/fuo_netease/nem.py", line 49, in ready_to_login
    cookies, exists = user.cache_get('cookies')
                      ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cache_get'
```

**Comment by cosven** [comment]
v0.9.7 should fix the problem https://github.com/feeluown/feeluown-netease/commit/f86dbffdd50259b58de29b36a3bdeb4521fac784
